USE accounts;
INSERT INTO abilities (name, description, cost, cooldown) VALUES
('Smite', 'Smite an enemy for 6 + 110% of your STR holy damage.', 35, 0),
('Shadow Bolt', 'Hurl a shadowy bolt dealing 5 + 115% of your INT shadow damage.', 40, 0),
('Frost Nova', 'Explode in frost dealing 3 + 100% of your INT ice damage to all enemies.', 50, 10),
('Piercing Shot', 'Fire a shot dealing 4 + 90% of your DEX damage that ignores armor.', 30, 0),
('Shockwave', 'Release a shockwave for 7 + 80% of your STR damage to all foes.', 45, 5),
('Quick Strike', 'Strike swiftly for 2 + 75% of your DEX damage.', 20, 0),
('Blizzard', 'Summon icy winds dealing 2 + 60% of your INT damage each second for 5s.', 60, 15),
('Searing Light', 'Burn undead with 8 + 120% of your INT holy damage.', 40, 5),
('Venom Cloud', 'Create a cloud dealing 1 + 40% of your DEX damage each second for 6s.', 35, 12),
('Earthquake', 'Shake the ground for 10 + 100% of your STR damage to all enemies.', 70, 20),
('Wind Slash', 'Cut with wind for 3 + 85% of your DEX damage.', 25, 0),
('Mind Spike', 'Lance the mind for 7 + 105% of your INT psychic damage.', 40, 0),
('Holy Blessing', 'Increase an ally\'s damage by 2 + 50% of your INT for 10s.', 30, 20),
('Arcane Shield', 'Conjure a barrier absorbing 5 + 150% of your INT damage for 15s.', 45, 15),
('Battle Cry', 'Increase all allies\' STR by 5 + 30% of your STR for 10s.', 35, 20),
('Crippling Blow', 'Smash an enemy for 5 + 95% of your STR damage and slow them.', 30, 8),
('Shadowstep', 'Blink behind a foe dealing 5 + 95% of your DEX damage.', 25, 5),
('Meteor', 'Call a meteor for 12 + 130% of your INT fire damage to all enemies.', 80, 30),
('Chain Lightning', 'Zap a foe for 6 + 110% of your INT damage, jumping to others.', 55, 8),
('Blood Pact', 'Deal 8 + 120% of your STR damage but take 2 + 50% of your STR recoil.', 40, 10),
('Enrage', 'Increase your damage by 5 + 40% of your STR for 8s.', 30, 25),
('Healing Wave', 'Heal the party for 4 + 100% of your INT HP.', 60, 20),
('Fortify', 'Grant a shield absorbing 3 + 60% of your INT damage for 8s.', 35, 15),
('Flame Strike', 'Smash the ground for 7 + 110% of your INT fire damage to all enemies.', 65, 12),
('Silencing Shot', 'Deal 4 + 80% of your DEX damage and silence for 3s.', 30, 8),
('Rend Armor', 'Rip armor dealing 3 + 70% of your STR damage and reducing defense.', 30, 10),
('Stunning Fist', 'Punch for 4 + 80% of your STR damage and stun briefly.', 25, 6),
('Smokescreen', 'Obscure the area increasing dodge by 5 + 40% of your DEX for 6s.', 30, 18),
('Magic Missile', 'Launch a missile dealing 3 + 80% of your INT arcane damage.', 20, 0),
('Thunderclap', 'Clap thunder for 6 + 100% of your STR damage to nearby foes.', 45, 12),
('Chain Heal', 'Heal an ally for 5 + 100% of your INT then bounce to another ally for 50% of that amount.', 50, 12),
('Prayer of Healing', 'Heal all allies for 6 + 80% of your INT.', 55, 15),
('Holy Light', 'Heal a single ally for 8 + 150% of your INT.', 45, 8),
('Guardian Ward', 'Grant a shield to yourself and nearby allies absorbing 4 + 120% of your INT damage for 15s.', 55, 25),
('Divine Aegis', 'Place a large barrier on an ally absorbing 8 + 250% of your INT damage for 15s.', 45, 20);
