USE accounts;
INSERT INTO abilities (name, description, cost, cooldown) VALUES
('Fire Slash', 'Cleave a foe with flaming steel dealing 4 + 100% of your STR as fire damage.', 0, 0),
('Shield Bash', 'Drive your shield into an enemy for 3 + 80% of your STR damage and briefly stun.', 0, 0),
('Ice Arrow', 'Shoot a frozen arrow dealing 3 + 90% of your DEX as ice damage.', 0, 0),
('Frost Trap', 'Plant a trap that bursts for 2 + 80% of your DEX ice damage and slows 30% for 4s.', 0, 0),
('Lightning Bolt', 'Call down lightning dealing 4 + 110% of your INT as shock damage.', 0, 0),
('Static Field', 'Electrocute nearby foes for 2 + 50% of your INT lightning damage each second for 3s.', 0, 0),
('Backstab', 'Strike from shadows dealing 5 + 120% of your DEX damage.', 0, 0),
('Smoke Bomb', 'Shroud the area granting 15% +1% per 20 DEX dodge for 5s.', 0, 0),
('Stone Skin', 'Harden the target reducing damage taken by 20% +1% per 30 STR for 6s.', 0, 0),
('Ground Slam', 'Smash the ground dealing 5 + 100% of your STR damage to nearby enemies.', 0, 0),
('Sand Slash', 'Slice with sandy edge for 4 + 90% of your STR damage and blind for 1s.', 0, 0),
('Mirage', 'Create an illusion increasing dodge by 10% +1% per 15 DEX for 8s.', 0, 0),
('Water Bolt', 'Launch pressurized water for 4 + 100% of your INT damage.', 0, 0),
('Bubble Shield', 'Encapsulate an ally absorbing 5 + 150% of your INT damage for 6s.', 0, 0),
('Magic Missile', 'Fire a magical bolt dealing 3 + 80% of your INT arcane damage.', 0, 0),
('Mana Shield', 'Consume mana to absorb 50% +1% per 20 INT of incoming damage for 5s.', 0, 0),
('Thunder Strike', 'Electrify a foe for 5 + 100% of your INT lightning damage.', 0, 0),
('Guard Stance', 'Adopt a stance gaining 20% +1% per 25 STR reduced damage for 5s.', 0, 0),
('Blizzard', 'Unleash freezing winds dealing 2 + 60% of your INT damage each second for 6s.', 0, 0),
('Ice Barrier', 'Raise ice shielding 5 + 120% of your INT damage for 8s.', 0, 0),
('Drain Life', 'Steal 3 + 70% of your INT HP from a target.', 0, 0),
('Rapid Shot', 'Loose two quick arrows each for 2 + 60% of your DEX damage.', 0, 0),
('Magma Fist', 'Punch with molten fury for 5 + 110% of your STR fire damage.', 0, 0),
('Molten Armor', 'Sheathe yourself in lava reducing damage by 15% +1% per 20 STR and burning attackers.', 0, 0),
('Thorn Volley', 'Fire a volley dealing 3 + 80% of your DEX damage to all foes in a line.', 0, 0),
('Nature''s Grasp', 'Root enemies for 3s and deal 2 + 70% of your INT nature damage each second.', 0, 0),
('Dust Slash', 'Slash a foe for 3 + 85% of your STR damage and reduce their accuracy.', 0, 0),
('Mirage Step', 'Dash forward becoming untargetable for 0.5s and strike for 4 + 90% DEX damage.', 0, 0),
('Smite', 'Smite an enemy for 6 + 110% of your STR holy damage.', 0, 0),
('Twin Slash', 'Strike twice, each hit dealing 3 + 75% of your DEX damage.', 0, 0),
('Rally', 'Bolster allies increasing STR by 2 + 20% of your STR for 8s.', 0, 0),
('Chi Wave', 'Send forth energy healing allies for 4 + 90% of your INT or damaging enemies for the same.', 0, 0),
('Serenity', 'Calm yourself restoring 5 + 120% of your INT HP over 5s.', 0, 0),
('Shadow Bolt', 'Hurl darkness for 5 + 115% of your INT shadow damage.', 0, 0),
('Curse', 'Afflict a target reducing damage by 10% +1% per 20 INT for 10s.', 0, 0),
('Ice Slam', 'Smash foes with icy force for 6 + 105% of your STR damage and slow them.', 0, 0),
('Freeze Aura', 'Emit chilling air dealing 1 + 50% INT damage per second and slowing nearby enemies.', 0, 0),
('Shock Arrow', 'Shoot an electrified arrow dealing 3 + 85% DEX lightning damage.', 0, 0),
('Quickstep', 'Leap aside increasing dodge by 15% +1% per 20 DEX for 3s.', 0, 0),
('Raise Skeleton', 'Summon a skeleton minion scaling with 50% of your INT.', 0, 0),
('Life Tap', 'Sacrifice 5% of max HP to restore 5 + 150% of your INT mana.', 0, 0),
('Riposte', 'Block then counter for 4 + 90% STR damage when attacked within 2s.', 0, 0),
('Lunge', 'Charge forward striking for 4 + 100% STR damage.', 0, 0),
('Entangle', 'Root a foe for 3s dealing 2 + 60% INT nature damage.', 0, 0),
('Healing Rain', 'Heal allies in the area for 3 + 80% INT HP every 2s for 6s.', 0, 0),
('Void Slash', 'Rend a foe with void energy for 5 + 100% STR shadow damage.', 0, 0),
('Dark Shield', 'Conjure a barrier absorbing 5 + 120% INT damage and reflecting 20% of damage taken.', 0, 0),
('Chain Lightning', 'Zap a foe for 4 + 100% INT damage then jump to two more targets.', 0, 0),
('Static Shield', 'Gain a shield for 5 + 100% INT damage; attackers take 2 + 50% INT lightning.', 0, 0),
('Inferno', 'Engulf the area in flames dealing 6 + 110% INT fire damage each second for 4s.', 0, 0),
('Flame Aura', 'Wreathe yourself in fire dealing 2 + 40% INT damage to nearby enemies each second.', 0, 0),
('Frenzy', 'Enter a frenzy increasing damage by 20% +1% per 25 STR for 6s.', 0, 0),
('Iron Skin', 'Harden flesh reducing damage taken by 30% +1% per 25 STR for 5s.', 0, 0),
('Shadow Shot', 'Fire a dark projectile dealing 4 + 90% DEX shadow damage.', 0, 0),
('Holy Nova', 'Radiate holy light healing allies for 3 + 80% INT and damaging foes for the same.', 0, 0),
('Protective Ward', 'Grant an ally a shield absorbing 4 + 100% INT damage for 10s.', 0, 0),
('Boulder Toss', 'Hurl a boulder for 6 + 120% STR damage at an enemy.', 0, 0),
('Earthquake', 'Shake the earth dealing 5 + 100% STR damage to all enemies.', 0, 0),
('Poison Cloud', 'Release toxins dealing 2 + 60% DEX poison damage each second for 6s.', 0, 0),
('Acid Flask', 'Throw acid dealing 3 + 80% DEX damage and reducing armor by 20% for 6s.', 0, 0),
('Summon Imp', 'Summon an imp scaling with 60% of your INT to fight for you.', 0, 0),
('Warp', 'Teleport up to 15m +1m per 20 INT.', 0, 0),
('Flame Wing', 'Slash with fiery wings dealing 5 + 100% STR fire damage to adjacent foes.', 0, 0),
('Rebirth', 'Upon death revive with 20% +1% per 10 INT HP.', 0, 0),
('Ice Spear', 'Hurl a piercing spear for 5 + 110% INT ice damage.', 0, 0),
('Winged Charge', 'Rush a target and deal 4 + 90% STR damage, stunning for 1s.', 0, 0),
('Tempest', 'Create a storm dealing 3 + 80% INT lightning damage every second for 5s.', 0, 0),
('Overcharge', 'Increase spell damage by 15% +1% per 25 INT for 8s.', 0, 0),
('Soul Drain', 'Drain a foe for 4 + 100% INT shadow damage and heal for that amount.', 0, 0),
('Bone Shield', 'Summon bones absorbing 5 + 100% INT damage.', 0, 0),
('Pounce', 'Leap to an enemy dealing 4 + 90% DEX damage.', 0, 0),
('Camouflage', 'Blend with surroundings gaining 20% +1% per 20 DEX dodge for 6s.', 0, 0),
('Illusory Strike', 'Strike with illusion dealing 3 + 85% DEX arcane damage.', 0, 0),
('Blink', 'Instantly teleport 10m +0.5m per 10 INT.', 0, 0),
('Sandstorm', 'Whirl sand dealing 2 + 60% INT damage each second and reducing accuracy.', 0, 0),
('Royal Decree', 'Command allies increasing damage by 10% +1% per 20 INT for 8s.', 0, 0),
('Rune Shield', 'Etch runes granting a shield for 4 + 120% INT damage.', 0, 0),
('Hammer Strike', 'Smash with a hammer for 6 + 110% STR damage.', 0, 0),
('Dragon Breath', 'Exhale flames dealing 7 + 120% INT fire damage in a cone.', 0, 0),
('Wing Buffet', 'Knock back enemies with wings dealing 4 + 90% STR damage.', 0, 0),
('Ice Nova', 'Burst of frost dealing 4 + 100% INT damage to nearby foes.', 0, 0),
('Undead Thrall', 'Raise an undead servant scaling with 60% of your INT.', 0, 0),
('Thunder Breath', 'Breathe lightning dealing 7 + 120% INT damage in a cone.', 0, 0),
('Storm Surge', 'Call a surge dealing 5 + 110% INT lightning damage to all enemies.', 0, 0),
('Hellfire', 'Unleash demonic flames for 8 + 130% INT fire damage to all enemies.', 0, 0),
('Demonic Roar', 'Terrify enemies reducing damage by 15% +1% per 20 INT for 5s.', 0, 0),
('Radiant Slash', 'Slash with holy light for 5 + 100% STR holy damage.', 0, 0),
('Guardian Light', 'Heal an ally for 4 + 90% INT and grant 10% damage reduction for 6s.', 0, 0),
('Dark Dominion', 'Empower yourself with darkness increasing damage by 15% +1% per 25 INT for 10s.', 0, 0),
('Shadow Wave', 'Send a wave of shadows dealing 4 + 95% INT damage to enemies.', 0, 0),
('Shield Wall', 'Raise shields reducing damage taken by 40% +1% per 25 STR for 6s.', 0, 0),
('Earth Rend', 'Rip the earth dealing 7 + 120% STR damage to a line of foes.', 0, 0),
('Arcane Comet', 'Summon a comet for 6 + 110% INT arcane damage.', 0, 0),
('Mana Storm', 'Create a storm that drains 3 + 50% INT mana from enemies each second for 5s.', 0, 0),
('Bloodlust', 'Increase attack speed by 20% +1% per 30 STR and heal for 5% of damage dealt for 8s.', 0, 0),
('Cleave', 'Swing in an arc dealing 5 + 100% STR damage to nearby foes.', 0, 0),
('Toxic Breath', 'Exhale poison dealing 5 + 100% INT damage over 6s.', 0, 0),
('Scale Barrage', 'Launch razor scales each for 3 + 70% DEX damage at all enemies.', 0, 0),
('Guardian Ward', 'Grant a shield to yourself and nearby allies absorbing 4 + 120% INT damage for 15s.', 0, 0),
('Divine Aegis', 'Place a large barrier on an ally absorbing 8 + 250% INT damage for 15s.', 0, 0);
