USE accounts;
INSERT INTO abilities (name, description, cost, cooldown) VALUES
('Fire Slash', 'Ability description.', 0, 0),
('Shield Bash', 'Ability description.', 0, 0),
('Ice Arrow', 'Ability description.', 0, 0),
('Frost Trap', 'Ability description.', 0, 0),
('Lightning Bolt', 'Ability description.', 0, 0),
('Static Field', 'Ability description.', 0, 0),
('Backstab', 'Ability description.', 0, 0),
('Smoke Bomb', 'Ability description.', 0, 0),
('Stone Skin', 'Ability description.', 0, 0),
('Ground Slam', 'Ability description.', 0, 0),
('Sand Slash', 'Ability description.', 0, 0),
('Mirage', 'Ability description.', 0, 0),
('Water Bolt', 'Ability description.', 0, 0),
('Bubble Shield', 'Ability description.', 0, 0),
('Magic Missile', 'Ability description.', 0, 0),
('Mana Shield', 'Ability description.', 0, 0),
('Thunder Strike', 'Ability description.', 0, 0),
('Guard Stance', 'Ability description.', 0, 0),
('Blizzard', 'Ability description.', 0, 0),
('Ice Barrier', 'Ability description.', 0, 0),
('Drain Life', 'Ability description.', 0, 0),
('Rapid Shot', 'Ability description.', 0, 0),
('Magma Fist', 'Ability description.', 0, 0),
('Molten Armor', 'Ability description.', 0, 0),
('Thorn Volley', 'Ability description.', 0, 0),
('Nature''s Grasp', 'Ability description.', 0, 0),
('Dust Slash', 'Ability description.', 0, 0),
('Mirage Step', 'Ability description.', 0, 0),
('Smite', 'Ability description.', 0, 0),
('Twin Slash', 'Ability description.', 0, 0),
('Rally', 'Ability description.', 0, 0),
('Chi Wave', 'Ability description.', 0, 0),
('Serenity', 'Ability description.', 0, 0),
('Shadow Bolt', 'Ability description.', 0, 0),
('Curse', 'Ability description.', 0, 0),
('Ice Slam', 'Ability description.', 0, 0),
('Freeze Aura', 'Ability description.', 0, 0),
('Shock Arrow', 'Ability description.', 0, 0),
('Quickstep', 'Ability description.', 0, 0),
('Raise Skeleton', 'Ability description.', 0, 0),
('Life Tap', 'Ability description.', 0, 0),
('Riposte', 'Ability description.', 0, 0),
('Lunge', 'Ability description.', 0, 0),
('Entangle', 'Ability description.', 0, 0),
('Healing Rain', 'Ability description.', 0, 0),
('Void Slash', 'Ability description.', 0, 0),
('Dark Shield', 'Ability description.', 0, 0),
('Chain Lightning', 'Ability description.', 0, 0),
('Static Shield', 'Ability description.', 0, 0),
('Inferno', 'Ability description.', 0, 0),
('Flame Aura', 'Ability description.', 0, 0),
('Frenzy', 'Ability description.', 0, 0),
('Iron Skin', 'Ability description.', 0, 0),
('Shadow Shot', 'Ability description.', 0, 0),
('Holy Nova', 'Ability description.', 0, 0),
('Protective Ward', 'Ability description.', 0, 0),
('Boulder Toss', 'Ability description.', 0, 0),
('Earthquake', 'Ability description.', 0, 0),
('Poison Cloud', 'Ability description.', 0, 0),
('Acid Flask', 'Ability description.', 0, 0),
('Summon Imp', 'Ability description.', 0, 0),
('Warp', 'Ability description.', 0, 0),
('Flame Wing', 'Ability description.', 0, 0),
('Rebirth', 'Ability description.', 0, 0),
('Ice Spear', 'Ability description.', 0, 0),
('Winged Charge', 'Ability description.', 0, 0),
('Tempest', 'Ability description.', 0, 0),
('Overcharge', 'Ability description.', 0, 0),
('Soul Drain', 'Ability description.', 0, 0),
('Bone Shield', 'Ability description.', 0, 0),
('Pounce', 'Ability description.', 0, 0),
('Camouflage', 'Ability description.', 0, 0),
('Illusory Strike', 'Ability description.', 0, 0),
('Blink', 'Ability description.', 0, 0),
('Sandstorm', 'Ability description.', 0, 0),
('Royal Decree', 'Ability description.', 0, 0),
('Rune Shield', 'Ability description.', 0, 0),
('Hammer Strike', 'Ability description.', 0, 0),
('Dragon Breath', 'Ability description.', 0, 0),
('Wing Buffet', 'Ability description.', 0, 0),
('Ice Nova', 'Ability description.', 0, 0),
('Undead Thrall', 'Ability description.', 0, 0),
('Thunder Breath', 'Ability description.', 0, 0),
('Storm Surge', 'Ability description.', 0, 0),
('Hellfire', 'Ability description.', 0, 0),
('Demonic Roar', 'Ability description.', 0, 0),
('Radiant Slash', 'Ability description.', 0, 0),
('Guardian Light', 'Ability description.', 0, 0),
('Dark Dominion', 'Ability description.', 0, 0),
('Shadow Wave', 'Ability description.', 0, 0),
('Shield Wall', 'Ability description.', 0, 0),
('Earth Rend', 'Ability description.', 0, 0),
('Arcane Comet', 'Ability description.', 0, 0),
('Mana Storm', 'Ability description.', 0, 0),
('Bloodlust', 'Ability description.', 0, 0),
('Cleave', 'Ability description.', 0, 0),
('Toxic Breath', 'Ability description.', 0, 0),
('Scale Barrage', 'Ability description.', 0, 0);
